### ISSUE TITLE
Crash when accessing location twice

### ISSUE THREAD

**Issue by SimonIT** [BaseflowIT/flutter-permission-handler#88]
## 🐛 Bug Report

See BaseflowIT/flutter-geolocator#131

I think it's more related to this plugin then the geolocator plugin.

My stacktrace:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
    <asynchronous suspension>
    #2      PermissionHandler.requestPermissions (package:permission_handler/src/permission_handler.dart:66:30)
    <asynchronous suspension>
    #3      Geolocator._getLocationPermission (package:geolocator/geolocator.dart:184:16)
    <asynchronous suspension>
    #4      Geolocator.getPositionStream (package:geolocator/geolocator.dart:162:47)
    <asynchronous suspension>
    #5      new RestaurantWidgetState.<anonymous closure> (package:taurant_app/widgets.dart:208:22)
    #6      _rootRunUnary (dart:async/zone.dart:1132:38)
    #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
    #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
    #10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
    #11     Future._complete (dart:async/future_impl.dart:473:7)
    #12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
    #13     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
    #14     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
    #15     Geolocator.isLocationServiceEnabled (package:geolocator/geolocator.dart)
    <asynchronous suspension>
    #16     new RestaurantWidgetState (package:taurant_app/widgets.dart:206:18)
    #17     RestaurantWidget.createState (package:taurant_app/widgets.dart:200:12)
    #18     new StatefulElement (package:flutter/src/widgets/framework.dart:3804:25)
    #19     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:805:38)
    #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:40)
    #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
    #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
    #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
    #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
    #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
    #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
    #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
    #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
    #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
    #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
    #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
    #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
    #38     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
    #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
    #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
    #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #43     ComponentElement._firstBuild (package:flutter/src
```

**Comment by mvanbeusekom** [comment]
@SimonIT this can happen when you request permissions multiple times without waiting for the initial result to return. We have seen this happen when developers use the `Permission Handler` or `Geolocator` plugin directly from their `Widget build(BuildContext context) { ... }` method (this method can be called multiple times in rapid succession by the Flutter framework to layout the widget). 

The best way around this problem is to request permissions from a method that you are sure is executed only once (e.g. the `void initState() { ... }` method from a stateful widget). After that you can safely use the `Geolocator` plugin to get location updates from anywhere in your code.
